services:
  - type: web
    name: spring-movie-api
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/ems-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://khansahabas07:7860@cluster0.shhnwox.mongodb.net/MoviesAPI?retryWrites=true&w=majority
